"""Independent, evidence-aware Khalkha frontend and research utilities.

The package stays independent of VocalRender and preserves unresolved
pronunciation explicitly. Morphology and context labels remain orthographic
evidence; callers inject resource paths when local data is required.
"""

from .allophones import AllophoneResolver, AllophoneRule, PhonologicalEnvironment
from .benchmark import (
    AudioSource,
    AudioTake,
    BenchmarkItem,
    BenchmarkManifest,
    EvaluationStatus,
    Lexicality,
    ManualRating,
    ValidationError,
    load_audio_takes,
    load_benchmark,
    load_ratings,
    load_manifest,
    validate_related,
)
from .context_mining import (
    FrequencyRecord,
    OrthographicCandidate,
    candidate_to_dict,
    mine_frequency,
    mine_unimorph,
    mine_word,
    read_frequency_list,
)
from .g2p import ConservativeG2PResolver, G2PResult
from .morphology import (
    DerivationRow,
    MorphAnalysis,
    MorphologyFormatError,
    MorphologyLookup,
    Segmentation,
    UniMorphKhalkha,
    analyze_word,
    segment_morphemes,
)
from .normalize import normalize_text
from .phones import PhoneDefinition, PhoneRegistry
from .resources import ResourcePaths, ResourceProblem, default_resource_paths
from .syllabify import ConservativeSyllabifier, Syllabifier
from .tokenizer_audit import (
    AuditSample,
    TokenizationRecord,
    TokenizerSnapshot,
    aggregate_by_benchmark_group,
    aggregate_by_character,
    aggregate_by_word_length,
    aggregate_records,
    collect_benchmark,
    collect_frequency,
    collect_special_probes,
    collect_unimorph,
    percentile,
    sha256_file,
    tokenize_sample,
    word_length_bucket,
)
from .types import (
    EvidenceRef,
    FrontendResult,
    NormalizedText,
    PhoneCandidate,
    PhonemeCandidate,
    PronunciationOverride,
    PronunciationUnit,
    ResolutionStatus,
    KhalkhaScore,
    LyricScoreUnit,
    SyllableCandidate,
    TextIssue,
    TextIssueKind,
    VocalRenderScoreEntry,
)
from .evidence import load_evidence_registry, require_evidence
from .native_study import (
    ContextAnnotation,
    Quota,
    diversity_vector,
    hash_item,
    load_context_annotations,
    load_quotas,
    quota_count,
    quota_satisfied,
    select_group,
    validate_source_span,
)
from .vocalrender_adapter import (
    ScoreAdapterError,
    ScoreNote,
    from_vocalrender_entry,
    to_vocalrender_entry,
    validate_vocalrender_entry,
)

__all__ = [
    "AllophoneResolver",
    "AllophoneRule",
    "AudioSource",
    "AudioTake",
    "ContextAnnotation",
    "AuditSample",
    "BenchmarkItem",
    "BenchmarkManifest",
    "ConservativeG2PResolver",
    "ConservativeSyllabifier",
    "DerivationRow",
    "EvaluationStatus",
    "EvidenceRef",
    "FrequencyRecord",
    "FrontendResult",
    "G2PResult",
    "KhalkhaScore",
    "Lexicality",
    "Quota",
    "LyricScoreUnit",
    "ManualRating",
    "MorphAnalysis",
    "MorphologyFormatError",
    "MorphologyLookup",
    "NormalizedText",
    "OrthographicCandidate",
    "PhoneCandidate",
    "PhoneDefinition",
    "PhoneRegistry",
    "PhonemeCandidate",
    "PhonologicalEnvironment",
    "PronunciationOverride",
    "PronunciationUnit",
    "ResolutionStatus",
    "ResourcePaths",
    "ResourceProblem",
    "Segmentation",
    "SyllableCandidate",
    "ScoreAdapterError",
    "ScoreNote",
    "Syllabifier",
    "TextIssue",
    "TextIssueKind",
    "TokenizationRecord",
    "TokenizerSnapshot",
    "UniMorphKhalkha",
    "ValidationError",
    "VocalRenderScoreEntry",
    "aggregate_by_benchmark_group",
    "aggregate_by_character",
    "aggregate_by_word_length",
    "aggregate_records",
    "analyze_word",
    "candidate_to_dict",
    "collect_benchmark",
    "collect_frequency",
    "collect_special_probes",
    "collect_unimorph",
    "default_resource_paths",
    "diversity_vector",
    "from_vocalrender_entry",
    "load_benchmark",
    "load_audio_takes",
    "load_context_annotations",
    "load_evidence_registry",
    "load_manifest",
    "load_ratings",
    "load_quotas",
    "mine_frequency",
    "mine_unimorph",
    "mine_word",
    "normalize_text",
    "hash_item",
    "quota_count",
    "quota_satisfied",
    "require_evidence",
    "select_group",
    "validate_related",
    "validate_source_span",
    "percentile",
    "read_frequency_list",
    "segment_morphemes",
    "to_vocalrender_entry",
    "validate_vocalrender_entry",
    "sha256_file",
    "tokenize_sample",
    "word_length_bucket",
]
